// Departamentos y ciudades de Paraguay
export const DEPARTAMENTOS_PARAGUAY = [
  { id: "ASU", nombre: "Asunción" },
  { id: "CON", nombre: "Concepción" },
  { id: "SAN", nombre: "San Pedro" },
  { id: "COR", nombre: "Cordillera" },
  { id: "GUA", nombre: "Guairá" },
  { id: "CAA", nombre: "Caaguazú" },
  { id: "CAZ", nombre: "Caazapá" },
  { id: "ITA", nombre: "Itapúa" },
  { id: "MIS", nombre: "Misiones" },
  { id: "PAR", nombre: "Paraguarí" },
  { id: "APY", nombre: "Alto Paraná" },
  { id: "CEN", nombre: "Central" },
  { id: "NEE", nombre: "Ñeembucú" },
  { id: "AMA", nombre: "Amambay" },
  { id: "CAN", nombre: "Canindeyú" },
  { id: "PRH", nombre: "Presidente Hayes" },
  { id: "BOQ", nombre: "Boquerón" },
  { id: "APG", nombre: "Alto Paraguay" },
]

export const CIUDADES_PARAGUAY: Record<string, string[]> = {
  ASU: ["Asunción"],
  CON: [
    "Concepción",
    "Belén",
    "Horqueta",
    "Loreto",
    "San Carlos del Apa",
    "San Lázaro",
    "Yby Yaú",
    "Azotey",
    "Paso Barreto",
    "Sargento José Félix López",
  ],
  SAN: [
    "San Pedro de Ycuamandiyú",
    "Antequera",
    "Choré",
    "General Elizardo Aquino",
    "Itacurubí del Rosario",
    "Lima",
    "Nueva Germania",
    "San Estanislao",
    "San Pablo",
    "Tacuatí",
    "Unión",
    "25 de Diciembre",
    "Villa del Rosario",
    "General Resquín",
    "Yataity del Norte",
    "Guayaibí",
    "Capiibary",
    "Santa Rosa del Aguaray",
    "Yrybucuá",
    "Liberación",
  ],
  COR: [
    "Caacupé",
    "Altos",
    "Arroyos y Esteros",
    "Atyrá",
    "Caraguatay",
    "Emboscada",
    "Eusebio Ayala",
    "Isla Pucú",
    "Itacurubí de la Cordillera",
    "Juan de Mena",
    "Loma Grande",
    "Mbocayaty del Yhaguy",
    "Nueva Colombia",
    "Piribebuy",
    "Primero de Marzo",
    "San Bernardino",
    "San José Obrero",
    "Santa Elena",
    "Tobatí",
    "Valenzuela",
  ],
  GUA: [
    "Villarrica",
    "Borja",
    "Capitán Mauricio José Troche",
    "Coronel Martínez",
    "Félix Pérez Cardozo",
    "General Eugenio A. Garay",
    "Independencia",
    "Itapé",
    "Iturbe",
    "José Fassardi",
    "Mbocayaty",
    "Natalicio Talavera",
    "Ñumí",
    "San Salvador",
    "Yataity",
    "Doctor Botrell",
    "Paso Yobái",
    "Tebicuary",
  ],
  CAA: [
    "Coronel Oviedo",
    "Caaguazú",
    "Carayaó",
    "Doctor Cecilio Báez",
    "Santa Rosa del Mbutuy",
    "Doctor Juan Manuel Frutos",
    "Repatriación",
    "Nueva Londres",
    "San Joaquín",
    "San José de los Arroyos",
    "Yhú",
    "Doctor Juan Eulogio Estigarribia",
    "Raúl Arsenio Oviedo",
    "José Domingo Ocampos",
    "Mariscal Francisco Solano López",
    "La Pastora",
    "3 de Febrero",
    "Simón Bolívar",
    "Vaquería",
    "Tembiaporá",
    "Nueva Toledo",
    "Mcal. José Félix Estigarribia",
  ],
  CAZ: [
    "Caazapá",
    "Abaí",
    "Buena Vista",
    "Doctor Moisés S. Bertoni",
    "General Higinio Morínigo",
    "Maciel",
    "San Juan Nepomuceno",
    "Tavaí",
    "Yegros",
    "Yuty",
    "3 de Mayo",
  ],
  ITA: [
    "Encarnación",
    "Bella Vista",
    "Cambyretá",
    "Capitán Meza",
    "Capitán Miranda",
    "Nueva Alborada",
    "Carmen del Paraná",
    "Coronel Bogado",
    "Carlos Antonio López",
    "Natalio",
    "Fram",
    "General Artigas",
    "General Delgado",
    "Hohenau",
    "Jesús",
    "Leandro Oviedo",
    "Obligado",
    "Mayor Otaño",
    "San Cosme y Damián",
    "San Pedro del Paraná",
    "San Rafael del Paraná",
    "Trinidad",
    "Edelira",
    "Tomás Romero Pereira",
    "Alto Verá",
    "La Paz",
    "Yatytay",
    "San Juan del Paraná",
    "Pirapó",
    "Itapúa Poty",
  ],
  MIS: [
    "San Juan Bautista",
    "Ayolas",
    "San Ignacio",
    "San Miguel",
    "San Patricio",
    "Santa María",
    "Santa Rosa",
    "Santiago",
    "Villa Florida",
    "Yabebyry",
  ],
  PAR: [
    "Paraguarí",
    "Acahay",
    "Caapucú",
    "Caballero",
    "Carapeguá",
    "Escobar",
    "General Bernardino Caballero",
    "La Colmena",
    "Mbuyapey",
    "Pirayú",
    "Quiindy",
    "Quyquyhó",
    "San Roque González de Santa Cruz",
    "Sapucai",
    "Tebicuarymí",
    "Yaguarón",
    "Ybycuí",
    "Ybytymí",
  ],
  APY: [
    "Ciudad del Este",
    "Presidente Franco",
    "Domingo Martínez de Irala",
    "Doctor Juan León Mallorquín",
    "Hernandarias",
    "Itakyry",
    "Juan Emilio O'Leary",
    "Ñacunday",
    "Yguazú",
    "Los Cedrales",
    "Minga Guazú",
    "San Cristóbal",
    "Santa Rita",
    "Naranjal",
    "Santa Rosa del Monday",
    "Minga Porá",
    "Mbaracayú",
    "San Alberto",
    "Iruña",
    "Santa Fe del Paraná",
    "Tavapy",
    "Doctor Raúl Peña",
  ],
  CEN: [
    "Areguá",
    "Capiatá",
    "Fernando de la Mora",
    "Guarambaré",
    "Itá",
    "Itauguá",
    "Lambaré",
    "Limpio",
    "Luque",
    "Mariano Roque Alonso",
    "Nueva Italia",
    "Ñemby",
    "San Antonio",
    "San Lorenzo",
    "Villa Elisa",
    "Villeta",
    "Ypacaraí",
    "Ypané",
    "J. Augusto Saldívar",
  ],
  NEE: [
    "Pilar",
    "Alberdi",
    "Cerrito",
    "Desmochados",
    "General José Eduvigis Díaz",
    "Guazú Cuá",
    "Humaitá",
    "Isla Umbú",
    "Laureles",
    "Mayor José Dejesús Martínez",
    "Paso de Patria",
    "San Juan Bautista de Ñeembucú",
    "Tacuaras",
    "Villa Franca",
    "Villa Oliva",
    "Villalbín",
  ],
  AMA: [
    "Pedro Juan Caballero",
    "Bella Vista Norte",
    "Capitán Bado",
    "Zanja Pytá",
    "Karapaí",
  ],
  CAN: [
    "Salto del Guairá",
    "Corpus Christi",
    "Curuguaty",
    "General Francisco Caballero Álvarez",
    "Itanará",
    "Katueté",
    "La Paloma",
    "Nueva Esperanza",
    "Yasy Cañy",
    "Yby Pytá",
    "Ygatimí",
    "Ypejhú",
    "Villa Ygatimí",
  ],
  PRH: [
    "Villa Hayes",
    "Benjamín Aceval",
    "Nanawa",
    "José Falcón",
    "Puerto Pinasco",
    "Teniente Esteban Martínez",
    "Teniente Irala Fernández",
    "General José María Bruguez",
  ],
  BOQ: [
    "Filadelfia",
    "Loma Plata",
    "Mariscal Estigarribia",
    "Teniente 1° Manuel Irala Fernández",
  ],
  APG: [
    "Fuerte Olimpo",
    "Puerto Casado",
    "Bahía Negra",
    "Carmelo Peralta",
  ],
}

export function getCiudadesByDepartamento(departamentoId: string): string[] {
  return CIUDADES_PARAGUAY[departamentoId] || []
}

export function getDepartamentoNombre(departamentoId: string): string {
  const dep = DEPARTAMENTOS_PARAGUAY.find((d) => d.id === departamentoId)
  return dep?.nombre || departamentoId
}

// Generar ID aleatorio de 8 dígitos
export function generarIdNino(): string {
  return Math.floor(10000000 + Math.random() * 90000000).toString()
}
